//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : UserType.h
//  @ Date : 13.05.2025
//  @ Author :
//
//


#if !defined(_USERTYPE_H)
#define _USERTYPE_H


enum UserType {
	Student,
	Teacher
};

string userTypeToString(userType UserType) {
    if (userType == Student) return "student";
    else if (userType == Teacher) return "teacher";
    else return "invalid user type";
}

#endif  //_USERTYPE_H
